// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.reducerComponent("Example");

function make(_, _$1) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function (self) {
              "You've clicked this " + (String(self[/* state */1][/* count */0]) + " times(s)");
              var match = self[/* state */1][/* showDetails */2];
              return React.createElement("div", undefined, React.createElement("div", undefined, React.createElement("button", {
                                  onClick: (function () {
                                      return Curry._1(self[/* send */3], /* ToggleDetails */2);
                                    })
                                }, "Show/Hide My Details"), match ? React.createElement("div", undefined, React.createElement("label", undefined, "First Name : "), self[/* state */1][/* firstname */3], React.createElement("br", undefined), React.createElement("label", undefined, "Last Name : "), self[/* state */1][/* lastname */4], React.createElement("br", undefined), React.createElement("label", undefined, "Email : "), self[/* state */1][/* email */5], React.createElement("br", undefined), React.createElement("label", undefined, "Mobile : "), self[/* state */1][/* mobile */6], React.createElement("br", undefined)) : null), React.createElement("div", undefined, React.createElement("button", {
                                  onClick: (function () {
                                      return Curry._1(self[/* send */3], /* UpdateDetails */3);
                                    })
                                }, "Update My Details")));
            }),
          /* initialState */(function () {
              return /* record */[
                      /* count */0,
                      /* show */true,
                      /* showDetails */true,
                      /* firstname */"Sunil",
                      /* lastname */"K",
                      /* email */"sunil.k@example.com",
                      /* mobile */"09999999448"
                    ];
            }),
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */(function (action, state) {
              switch (action) {
                case 0 : 
                    return /* Update */Block.__(0, [/* record */[
                                /* count */state[/* count */0] + 1 | 0,
                                /* show */state[/* show */1],
                                /* showDetails */state[/* showDetails */2],
                                /* firstname */state[/* firstname */3],
                                /* lastname */state[/* lastname */4],
                                /* email */state[/* email */5],
                                /* mobile */state[/* mobile */6]
                              ]]);
                case 1 : 
                    return /* Update */Block.__(0, [/* record */[
                                /* count */state[/* count */0],
                                /* show */!state[/* show */1],
                                /* showDetails */state[/* showDetails */2],
                                /* firstname */state[/* firstname */3],
                                /* lastname */state[/* lastname */4],
                                /* email */state[/* email */5],
                                /* mobile */state[/* mobile */6]
                              ]]);
                case 2 : 
                    return /* Update */Block.__(0, [/* record */[
                                /* count */state[/* count */0],
                                /* show */state[/* show */1],
                                /* showDetails */!state[/* showDetails */2],
                                /* firstname */state[/* firstname */3],
                                /* lastname */state[/* lastname */4],
                                /* email */state[/* email */5],
                                /* mobile */state[/* mobile */6]
                              ]]);
                case 3 : 
                    return /* Update */Block.__(0, [/* record */[
                                /* count */state[/* count */0],
                                /* show */state[/* show */1],
                                /* showDetails */state[/* showDetails */2],
                                /* firstname */"Adam",
                                /* lastname */"Jones",
                                /* email */"a.jones@example.com",
                                /* mobile */"088946445585"
                              ]]);
                
              }
            }),
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
