// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var ReactDOMRe = require("reason-react/src/ReactDOMRe.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var CityInfo$ReactTemplate = require("./CityInfo.bs.js");
var Component1$ReactTemplate = require("./Component1.bs.js");
var Component2$ReactTemplate = require("./Component2.bs.js");
var FetchDogExample$ReactTemplate = require("./FetchDogExample.bs.js");

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, Component1$ReactTemplate.make("Hello!", /* array */[])), "index1");

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, Component2$ReactTemplate.make("Hello!", /* array */[])), "index2");

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, FetchDogExample$ReactTemplate.make(/* array */[])), "index3");

ReactDOMRe.renderToElementWithId(ReasonReact.element(/* None */0, /* None */0, CityInfo$ReactTemplate.make(/* array */[])), "index4");

/*  Not a pure module */
